language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email:
    - team@wpscan.org
